### ISSUE TITLE
Using async/await will increase the resemblance of the two

### ISSUE THREAD

**Issue by itaditya** [pazams/go-for-javascript-developers#15]
Using `.then()` will surely confuse new programmers, because they don't know what Promises are. 
As code with `async/await` is synchronous looking, it would definitely improve user's understanding. 

I can make a PR regarding this.

**Comment by pazams** [comment]
Hi @itaditya, thanks for the suggestion.
A PR is welcomed! Though since es8 was finalised just 7 months ago and a lot of companies are using nodejs versions below 7.0 (without transpiling), I would prefer to keep `.then` and add a second example with `async/await`.
On a similar subject I just noted that this is out of date:

> Note the async/await mechanism, which is in draft, will consolidate both worlds by having asynchronous errors being handled inside try/catch blocks.

It should be changed to:

Note the async / await constructs consolidates both worlds by having asynchronous errors being handled inside try/catch blocks.

Feel free to include in your PR as well.

**Comment by itaditya** [comment]
Ok then I'll make one today :)

**Comment by pazams** [comment]
Closed with https://github.com/pazams/go-for-javascript-developers/pull/16
